"""add year

Revision ID: 2f10e6e28f99
Revises: 990700621772
Create Date: 2025-04-06 22:17:12.385639

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2f10e6e28f99'
down_revision: Union[str, None] = '990700621772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'industry',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'industry',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
