"""add year

Revision ID: 9719d6cf0090
Revises: a57dbd7b5615
Create Date: 2025-04-06 22:27:29.786296

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9719d6cf0090'
down_revision: Union[str, None] = 'a57dbd7b5615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_url_key', 'companies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('companies_url_key', 'companies', ['url'])
    # ### end Alembic commands ###
