"""Initial migration

Revision ID: 99ba9bd9159e
Revises: 
Create Date: 2025-04-06 23:24:34.512122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '99ba9bd9159e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=False),
    sa.Column('total_employees', sa.Integer(), nullable=False),
    sa.Column('headquarters_city', sa.String(), nullable=False),
    sa.Column('employee_locations', sa.JSON(), nullable=True),
    sa.Column('employee_growth', sa.JSON(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
